---
title: "get_observations_dev"
author: "N.M. Tarr"
date: "2023-08-28"
output: html_document
---

```{r setup, include=TRUE, message=TRUE, warning=TRUE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE)
knitr::opts_knit$set(root.dir = '~/Documents/NCBA/species/')
```

# Function
```{r}
get_observations_dev <- function(species, dataset = "AtlasCache", 
                                 drop_columns = TRUE, fields = NULL,
                                 ncba_config) {
  # Returns a data frame of species observations
  # 
  # Description:
  #   Retrieves the observation records for a species from either the NCBA 
  #   database or from a downloaded copy of the EBD.  If data is requested from
  #   the Atlas Cache, then NCBA columns that are not found in the EBD datasets
  #   can be dropped or retained.
  # 
  # Parameters:
  # species -- common name of the species
  # dataset -- either "EBD" for a downloaded eBird dataset or "AtlasCache" for
  #   the NCBA mongodb.
  # drop_columns -- whether to drop non-eBird columns from the output data frame
  # fields -- a list of field names to retrieve.  Default of NULL returns all 
  #   fields.  
  # ncba_config -- config file with NCBA MongoDB username and password
  
  if (dataset == "AtlasCache") {
    # Connect to a specific collection (table)
    connection_ebd <- connect_ncba_db(ncba_config = ncba_config, 
                                      database = "ebd_mgmt", 
                                      collection = "ebd")
  
    # Make a query
    query <- str_interp('{"OBSERVATIONS.COMMON_NAME":"${species}"}')
    
    # Condition on whether fields were provided.
    if (is.na(fields) == TRUE) {
      nc_data <- connection_ebd$find(query) %>%
        unnest(cols = (c(OBSERVATIONS))) #%>% # Expand observations
        #filter(COMMON_NAME == species)
    } else {
      nc_data <- connection_ebd$find(query, fields = fields) %>%
        unnest(cols = (c(OBSERVATIONS)))
    }
    
    # format columns to the standard analysis format (ebd format)
    records <- to_ebd_format(nc_data, drop=drop_columns)
  }
    
  if (dataset == "EBD") {
    print("NOT AVAILABLE YET")
  }
}
```

# Usage
This demo requires the tidyverse packages.
```{r}
library(tidyverse)
```

Load the NCBA functions because this function relies upon the output from some of them.
```{r}
setwd("~/Code/NCBA/resources")
source("ncba_functions.R")

ncba_config <- "~/Documents/NCBA/Scripts/ncba_config.R"
```

Retrieve observation functions with the function
```{r}
obs <- get_observations_dev(species = "Willow Flycatcher", 
                            dataset = "AtlasCache", 
                            drop_columns = TRUE, ncba_config = ncba_config)
```

# Tests

# Speed
```{r}
# Run the function 30 times and record the runtime
time <- c()
for (i in 1:30) {
  time1 <- proc.time()
  get_observations_dev(species = "Willow Flycatcher", dataset = "AtlasCache", 
                       drop_columns = TRUE, ncba_config = ncba_config)
  time[i] <- proc.time() - time1
}

# Print the descriptive statistics
print(summary(time))
```

