---
title: "dev_observer_block_complete_summary"
author: "N.M. Tarr"
date: "2023-10-06"
output: word_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
setwd("~/Code/NCBA/resources")
source("ncba_functions.R")

knitr::opts_knit$set(root.dir = work_dir)
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE)
```


# Purpose


# Function
```{r}
library(auk)
observer <- "obsr1000095"


# Get a data frame of the observer's checklists, join get PRIORITY
checklists <- get_checklists(observer = observer) %>%
    to_EBD_format() %>%
    auk_unique(checklists_only = TRUE)

# ------------------------------------------------------------
library(auk)

# Get a data frame of atlas blocks with the priority column
blocks <- get_blocks(spatial = FALSE,
                     fields = c("ID_BLOCK_CODE", "PRIORITY"))




# <<<<<<<<<< block type by checklist type (BLOCK COUNT) >>>>>>>>>>>>>>>>>>>>>>>>>>

 # Drop excess columns in checklists and join to get PRIORITY
checks0 <- checklists %>%
    select(c("atlas_block", "all_species_reported", "sampling_event_identifier")) %>%
    left_join(blocks, by = join_by("atlas_block" == "ID_BLOCK_CODE")) %>%
    data.frame()

# Replace the values in PRIORITY.  0 = non-priority, 1 = priority.
checks0$PRIORITY <- ifelse(checks0$PRIORITY == 1, "priority", "non-priority")

# Replace the values in all_species_reported.  TRUE = complete, FALSE = incomplete.
checks0$all_species_reported <- ifelse(checks0$all_species_reported == TRUE, 
                                       "complete", "incomplete")

# Make a summary data frame with PRIORITY values as the index, all_species_reported values
# as the columns, and the number of blocks (i.e., atlas_block) in each cell.
obs3 <- checks0 %>%
    group_by(PRIORITY, all_species_reported) %>%
    summarise(n = n_distinct(atlas_block)) %>%
    rename("block_type" = PRIORITY,
           "checklist_type" = all_species_reported,
           "block_count" = n) %>%
    data.frame() %>%
    pivot_wider(names_from = checklist_type,
                values_from = block_count,
                values_fill = list(block_count = 0)) %>%
                arrange(desc(block_type))


# <<<<<<<<<<<<< block type by checklist type (CHECKLIST COuNT) >>>>>>>>>>>>>>>>>>>>>>>>>>
# Make a summary data frame with PRIORITY values as the index, all_species_reported values
# as the columns, and the number of checklists (i.e., sampling_event_identifier) in each cell.
obs4 <- checks0 %>%
    group_by(PRIORITY, all_species_reported) %>%
    summarise(n = n_distinct(sampling_event_identifier)) %>%
    rename("block_type" = PRIORITY,
           "checklist_type" = all_species_reported,
           "checklist_count" = n) %>%
    data.frame() %>%
    pivot_wider(names_from = checklist_type,
                values_from = checklist_count,
                values_fill = list(checklist_count = 0)) %>%
                arrange(desc(block_type))

# Add a row at the bottom for the column totals.
obs4 <- obs4 %>%
    add_row(block_type = "either",
            complete = sum(obs4$complete),
            incomplete = sum(obs4$incomplete)) %>%
            data.frame()


```

# Usage
```{r}

```


```{r}
```


# Tests
```{r}

```


# Speed
Run the function several times to get descriptive statistics.
```{r}
# Get the data
records <- get_checklists(observer = "obsr1000095", project = NULL) %>%
to_EBD_format()

# Run the function 10 times and record the runtime
time <- c()
for (i in 1:10) {
  time1 <- proc.time()
  protocol_table(records)
  t <- proc.time() - time1
  time[i] <- t["elapsed"]
}

# Print the descriptive statistics
print(summary(time))
```