---
title: "dev_observer_block_category_summary"
author: "N.M. Tarr"
date: "2023-10-06"
output: word_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
setwd("~/Code/NCBA/resources")
source("ncba_functions.R")

knitr::opts_knit$set(root.dir = work_dir)
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE)
```


# Purpose


# Function
```{r}
library(auk)
observer <- "obsr1000095"

# Get a data frame of the observer's observations, join get PRIORITY
observations <- get_observations(observer = observer) %>%
    to_EBD_format() %>%
    auk_unique()



# ------------------------------------------------------------
library(auk)

# Get a data frame of atlas blocks with the priority column
blocks <- get_blocks(spatial = FALSE,
                     fields = c("ID_BLOCK_CODE", "PRIORITY"))

# Drop excess columns in observations and join to get PRIORITY
obs0 <- observations %>%
    select(c("atlas_block", "common_name", "breeding_category")) %>%
    left_join(blocks, by = join_by("atlas_block" == "ID_BLOCK_CODE")) %>%
    data.frame()


# <<<<<<<<<< priority by SPECIES count >>>>>>>>>>>>>>>>>>>>>>>>>>

# Replace the values in breeding_category with words
obs0$breeding_category <- ifelse(obs0$breeding_category == "C4", "confirmed",
                                  ifelse(obs0$breeding_category == "C3", "probable",
                                         ifelse(obs0$breeding_category == "C2", "possible",
                                                ifelse(obs0$breeding_category == "C1", "observed", NA))))

# Fill NA breeding_category values with "observed"
obs0$breeding_category <- ifelse(is.na(obs0$breeding_category), "observed", obs0$breeding_category)

# Replace the values in PRIORITY.  0 = non-priority, 1 = priority.
obs0$PRIORITY <- ifelse(obs0$PRIORITY == 0, "non-priority", "priority")

# Make a summary data frame with PRIORITY values as the index, breeding_category values
# as the columns, and the number of species (i.e., common_names) in each cell.
obs1 <- obs0 %>%
    group_by(PRIORITY, breeding_category) %>%
    summarise(n = n_distinct(common_name)) %>%
    rename("block_type" = PRIORITY,
           "breeding_category" = breeding_category,
           "species_count" = n) %>%
    data.frame() %>%
    pivot_wider(names_from = breeding_category,
                values_from = species_count,
                values_fill = list(species_count = 0)) %>%
                arrange(desc(block_type))

# Reorder the columns to confirmed, probable, possible, observed
obs1 <- obs1[, c(1, 2, 5, 4, 3)]

# Add a row to the bottom of the table with the number of species with
# each breeding_category value from any atlas block.
obs1 <- obs1 %>%
    add_row(block_type = "either",
            confirmed = n_distinct(obs0$common_name[obs0$breeding_category == "confirmed"]),
            probable = n_distinct(obs0$common_name[obs0$breeding_category == "probable"]),
            possible = n_distinct(obs0$common_name[obs0$breeding_category == "possible"]),
            observed = n_distinct(obs0$common_name[obs0$breeding_category == "observed"])) %>%
            data.frame()


# <<<<<<<<<< priority by BLOCK count >>>>>>>>>>>>>>>>>>>>>>>>>>

# Make a summary data frame with PRIORITY values as the index, breeding_category values
# as the columns, and the number of blocks (i.e., atlas_block) in each cell.
obs2 <- obs0 %>%
    group_by(PRIORITY, breeding_category) %>%
    summarise(n = n_distinct(atlas_block)) %>%
    rename("block_type" = PRIORITY,
           "breeding_category" = breeding_category,
           "block_count" = n) %>%
    data.frame() %>%
    pivot_wider(names_from = breeding_category,
                values_from = block_count,
                values_fill = list(block_count = 0)) %>%
                arrange(desc(block_type))

# Reorder the columns to confirmed, probable, possible, observed
obs2 <- obs2[, c(1, 2, 5, 4, 3)]

# Add a row to the bottom of the table with column totals and assign block type to "either".
obs2 <- obs2 %>%
    add_row(block_type = "either",
            confirmed = sum(obs2$confirmed),
            probable = sum(obs2$probable),
            possible = sum(obs2$possible),
            observed = sum(obs2$observed)) %>%
            data.frame()


print("species")
print(obs1)

print("blocks")
print(obs2)

```

# Usage
```{r}

```


```{r}
```


# Tests
```{r}

```


# Speed
Run the function several times to get descriptive statistics.
```{r}
# Get the data
records <- get_checklists(observer = "obsr1000095", project = NULL) %>%
to_EBD_format()

# Run the function 10 times and record the runtime
time <- c()
for (i in 1:10) {
  time1 <- proc.time()
  protocol_table(records)
  t <- proc.time() - time1
  time[i] <- t["elapsed"]
}

# Print the descriptive statistics
print(summary(time))
```