---
title: "Single Species Summary Example - just a starting point."
author: "S.K Anderson"
date: "9/9/2021"
output: html_document
description: "Scott's tinkering"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Paths
```{r}
sp <- "American Goldfinch"
ebd_file <- "~/YOURPATH/ebd_US-NC_202103_202109_relJul-2021.txt"
EBD_output <- "~/YOURPATH/NCBA/Species/testSP.txt"
```

Load packages
```{r}
library(auk)
library(dplyr)
library(mongolite)
```

# MONGO DB
```{r}
source("mongo_credentials.r")
#> this is a read only account
HOST = "cluster0-shard-00-00.rzpx8.mongodb.net:27017"
DB = "ebd_mgmt"
COLLECTION = "ebd"
#> other relevant collections include: blocks and ebd_taxonomy

URI = sprintf("mongodb://%s:%s@%s/%s?authSource=admin&replicaSet=atlas-3olgg1-shard-0&readPreference=primary&ssl=true",MUSER(), MPASS(), HOST, DB)

#> connect to a specific collection (table)
m <- mongo(COLLECTION, url = URI)
print (m)

#> return record with the following SAMPLING_EVENT_IDENTIFIER
#> this query follows JSON based query syntax (see here for the basics: https://jeroen.github.io/mongolite/query-data.html#query-syntax)
#testdata <- m$find('{"SAMPLING_EVENT_IDENTIFIER":"S79697260"}')
Q = '{"OBSERVATIONS.COMMON_NAME":"Brown Creeper"}'
F = '{"SAMPLING_EVENT_IDENTIFIER":1, "OBSERVATION_DATE": 1, "NCBA_BLOCK":1, "DURATION_MINUTES": 1, "PROJECT_CODE":1, "LATITUDE":1, "LONGITUDE":1, "OBSERVATIONS.&":1}'

testdata <- m$find(query = Q, fields = F)
#> looks like it dumps it right into a dataframe? will have to work through how to get observations (sub-documents)
print(testdata)
print(testdata$OBSERVATIONS[[1]])
```

```{r}
testdata2 <- unnest(testdata, cols = (c(OBSERVATIONS)))
```


# EBD
Read the EBD database
```{r}
df1 <- ebd_file %>%
       # 1. reference file
       auk_ebd() %>%
       # 2. define filters
       auk_species(species = sp) %>%
       # 3. run filtering
       auk_filter(file = EBD_output, overwrite = TRUE) %>%
       # 4. read text file into r data frame
       read_ebd()
```

# Data Summaries
Summarize by breeding codes
```{r}
df2 <- df1 %>%
       # Summarize by number checklists within each block
       group_by(breeding_code) %>%
       summarize(reports=n())
```
