---
title: "Top eBirders by County"
author: "N.M. Tarr"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  rmdformats::downcute:
  html_document:
    df_print: paged
    code_folding: hide

---
# Purpose
Find the top eBirder in each county of North Carolina.


```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE)

library(dplyr)
library(auk)

# Reference the filtered checklist output file
filtered_checklists <- "~/Documents/NCBA/Data/filtered_checklists.txt"

# Read in the effort data (filtered checklist table).
checklists <- read_sampling(filtered_checklists)

comma <- function(x) format(x, digits=2, big.mark=",")
```

```{r filter}
# Further filtering of the sampling data can occur here.  For example, we may
# want to remove data from certain projects.
```

```{r top_eBirders_county}
by_county <- checklists %>%
  select(checklist_id, county, observer_id) %>%
  group_by(county, observer_id) %>%
  summarise(checklists = n()) %>%
  arrange(county) %>%
  group_by(county) %>%
  top_n(n=1)
knitr::kable(by_county, caption="Top eBirders in Each County of North Carolina")
```
