---
title: "Single Species Summary Development"
author: "N.M. Tarr"
date: "9/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set your paths and credentials here
```{r variables}
sp <- "American Goldfinch"
ebd_file <- ""
EBD_output <- ""

USER = ""
PASS = ""
```

```{r packages}
# Load packages
library(auk)
library(dplyr)
library(mongolite)
library(tidyr)
library(stringr)
```

# MongoDB
Read from the EBD collection
```{r read_mongo}
time1 <- proc.time()
# this is a read only account
HOST = "cluster0-shard-00-00.rzpx8.mongodb.net:27017"
DB = "ebd_mgmt"
COLLECTION = "ebd"
# other relevant collections include: blocks and ebd_taxonomy

URI = sprintf("mongodb://%s:%s@%s/%s?authSource=admin&replicaSet=atlas-3olgg1-shard-0&readPreference=primary&ssl=true",USER, PASS, HOST, DB)

# connect to a specific collection (table)
m <- mongo(COLLECTION, url = URI)

# return records for the species
# this query follows JSON based query syntax (see here for the basics: https://jeroen.github.io/mongolite/query-data.html#query-syntax)
query <- str_interp('{"OBSERVATIONS.COMMON_NAME":"${sp}"}')
mongodata <- m$find(query) %>%
             unnest(cols = (c(OBSERVATIONS))) %>% # Expand observations
             filter(COMMON_NAME == sp)
              
# Calculate processing time
mongotime <- proc.time() - time1

# Print number of records returned
print(paste("Records returned:", nrow(mongodata)))
print(paste("Runtime: ", mongotime[["elapsed"]]))
```

Summarize by breeding codes
```{r mongo_breeding}
mongodata2 <- mongodata %>%
              # Summarize by number checklists within each block
              group_by(BREEDING_CODE) %>%
              summarize(reports=n())
print(mongodata2)
```

# EBD/AUK
Read from an EBD file
```{r read_auk}
time1 <- proc.time()
aukdata <- ebd_file %>% 
           # 1. reference file
           auk_ebd() %>% 
           # 2. define filters
           auk_species(species = sp) %>% 
           # 3. run filtering
           auk_filter(file = EBD_output, overwrite = TRUE) %>% 
           # 4. read text file into r data frame
           read_ebd()

# Calculate processing time
auktime <- proc.time() - time1

# Print number of records returned
print(paste("Records returned:", nrow(aukdata)))
print(paste("Runtime: ", auktime[["elapsed"]]))
```

Summarize by breeding codes
```{r auk_breeding}
aukdata2 <- aukdata %>%
            # Summarize by number checklists within each block
            group_by(breeding_code) %>%
            summarize(reports=n())
print(aukdata2)
```